"""Adiciona imagem_paletrante a Evento

Revision ID: 05484f2267c4
Revises: 0cbbb4afd026
Create Date: 2025-06-07 15:48:32.640002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05484f2267c4'
down_revision = '0cbbb4afd026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_palestrante', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('imagem_palestrante')

    # ### end Alembic commands ###
