"""Remove campos pessoais redundantes do modelo Inscricao

Revision ID: 18862b9c0c0c
Revises: c5196f997b87
Create Date: 2025-06-09 16:54:11.108952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18862b9c0c0c'
down_revision = 'c5196f997b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_inscricoes_email'), type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_inscricoes_email'), ['email'])

    # ### end Alembic commands ###
