"""Adiciona modelos Categoria e Luta e ajusta Inscricao

Revision ID: 1ad9b881ed05
Revises: f179572b8384
Create Date: 2025-06-23 15:36:00.626776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad9b881ed05'
down_revision = 'f179572b8384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('ordem_na_chave', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('competidor1_id', sa.Integer(), nullable=True),
    sa.Column('competidor2_id', sa.Integer(), nullable=True),
    sa.Column('vencedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['competidor1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['competidor2_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['vencedor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_inscricoes_categoria_id_categorias', 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inscricoes_categoria_id_categorias', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    op.drop_table('lutas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
