"""Adiciona campos de perfil ao modelo User

Revision ID: 28615c698124
Revises: c6cd14fde35a
Create Date: 2025-06-09 13:40:53.953525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28615c698124'
down_revision = 'c6cd14fde35a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imagem_perfil', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('imagem_perfil')
        batch_op.drop_column('bio')
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###
