"""FASE 1: Adiciona campos de participante como opcionais a Inscricao

Revision ID: 5235c002f74d
Revises: df83438d3f88
Create Date: 2025-06-17 21:47:58.595247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5235c002f74d'
down_revision = 'df83438d3f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_participante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sobrenome_participante', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('cpf')
        batch_op.drop_column('idade')
        batch_op.drop_column('sobrenome_participante')
        batch_op.drop_column('nome_participante')

    # ### end Alembic commands ###
