"""Adiciona google_id ao modelo User para futuro login social

Revision ID: 810d4d776afb
Revises: b911b310c0a9
Create Date: 2025-06-30 11:28:38.969873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810d4d776afb'
down_revision = 'b911b310c0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
