"""Versão inicial completa do banco de dados

Revision ID: c2a290a82743
Revises: 
Create Date: 2025-06-09 17:45:38.171680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a290a82743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_equipe', sa.String(length=100), nullable=False),
    sa.Column('professor_responsavel', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_equipe')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_evento', sa.String(length=200), nullable=False),
    sa.Column('data_hora_evento', sa.DateTime(), nullable=False),
    sa.Column('palestrante', sa.String(length=100), nullable=True),
    sa.Column('imagem_palestrante', sa.String(length=300), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local_evento', sa.String(length=200), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('numero_vagas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('nome_completo', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('imagem_perfil', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricoes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('eventos')
    op.drop_table('equipes')
    # ### end Alembic commands ###
