"""Adiciona o campo email na tabela inscricoes

Revision ID: c6cd14fde35a
Revises: 1573403f6611
Create Date: 2025-06-08 18:19:34.930503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cd14fde35a'
down_revision = '1573403f6611'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
    # Aqui você pode usar SQL para preencher os emails existentes, por exemplo:
    op.execute("UPDATE inscricoes SET email = 'preencher@email.com' WHERE email IS NULL")
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.alter_column('email', nullable=False)
        batch_op.create_unique_constraint('uq_inscricoes_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
