"""empty message

Revision ID: d345ac8259d3
Revises: 18862b9c0c0c
Create Date: 2025-06-09 16:56:41.439900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd345ac8259d3'
down_revision = '18862b9c0c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_inscricoes_email'), type_='unique', if_exists=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_inscricoes_email'), ['email'])

    # ### end Alembic commands ###
