"""Adiciona campo pix_copia_e_cola a Evento

Revision ID: df83438d3f88
Revises: c2a290a82743
Create Date: 2025-06-11 20:48:02.245543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df83438d3f88'
down_revision = 'c2a290a82743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_copia_e_cola', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('pix_copia_e_cola')

    # ### end Alembic commands ###
