"""FASE 1.1: Adiciona campos de participante como opcionais a Inscricao

Revision ID: f179572b8384
Revises: 5235c002f74d
Create Date: 2025-06-17 22:00:28.091174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f179572b8384'
down_revision = '5235c002f74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('graduacao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('professor_responsavel', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inscricoes', schema=None) as batch_op:
        batch_op.drop_column('professor_responsavel')
        batch_op.drop_column('graduacao')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
